<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Enrise VPN Portal</title>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/extra.css" rel="stylesheet">
  </head>
  <body>
    <div class="navbar">
        <div class="container">
            <div class="navbar-inner">
                <a class="brand logoimage" href="http://www.enrise.com/"  target="_blank"><img alt="Enrise logo" src="img/header-logo.png"/></a>
                <a class="brand" href="index.php">VPN Portal</a>
                <ul class="nav">
                  <li><a href="index.php">Home</a></li>
                  {{LOGOUTBUTTON}}
                </ul>
            </div>
        </div>
    </div>
    
    <div class="container">
        {{CONTENT}}
    </div>

    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>